<script type="text/javascript">
if (annyang) {
	var flushSystemAction = function () {
		window.location.href = '<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/cache/flushSystem"); ?>';
	}
	var flushAllAction = function () { 
		window.location.href = '<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/cache/flushAllAction"); ?>';		
	}
	var cleanMediaAction = function () { 
		window.location.href = '<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/cache/cleanMediaAction"); ?>';		
	}
	var cleanImagesAction = function () { 
		window.location.href = '<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/cache/cleanImagesAction"); ?>';		
	}

	var cacheCommands = {
		'<?php echo Mage::helper('voice')->__('flush system'); ?>' 	: flushSystemAction,
		'<?php echo Mage::helper('voice')->__('flush all'); ?>'		: flushAllAction,
		'<?php echo Mage::helper('voice')->__('clean media'); ?>'	: cleanMediaAction,
		'<?php echo Mage::helper('voice')->__('clean images'); ?>'	: cleanImagesAction,
	};

	annyang.addCommands(cacheCommands);
}	
</script>